name: Release

on:
  push:
    branches:
      - main
      - develop

jobs:
  release:
    name: Release
    uses: ctfpilot/ci/.github/workflows/release.yml@v1.5.0-r.1
    permissions:
      contents: write
      packages: write
      id-token: write
    secrets:
      RELEASE_GH_TOKEN: ${{ secrets.RELEASE_GH_TOKEN }}
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
    with:
      repository: ctfpilot/challenge-toolkit
      plugins: "semantic-release-pypi"
      ENVIRONMENT: Release
      INSTALL_UV: true

